CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  strategy_id INT,
  role VARCHAR(50) DEFAULT 'user',
  FOREIGN KEY (strategy_id) REFERENCES strategy(strategy_id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS strategy (
  strategy_id SERIAL PRIMARY KEY,
  strategy_name VARCHAR(255) UNIQUE NOT NULL
);